SYCL release packages
- properly exit Windows jobs
- Windows release Ninja support, incl WA
- fix Windows zip sign test
- GPU beta
- Re-add /STACK increase on Windows

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -56,6 +56,27 @@ jobs:
       artifact-out: release-linux
       artifact-path: build_release/*.gz
 
+  release-sycl-linux:
+    needs: pdf
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
+    secrets: inherit
+    with:
+      force-delete: true    # guarantees .gitattributes are respected in working dir
+      image: ubuntu:22.04
+      env-from-files: .github/workflows/dpcpp-release.env
+      level-zero-version: public/1.12.0 # for ispcrt
+      cmd: |
+        module load cmake/3.25.3
+        update-alternatives --set mpi /usr/bin/mpicc.mpich
+        update-alternatives --set mpirun /usr/bin/mpirun.mpich
+        update-alternatives --set mpi-x86_64-linux-gnu /usr/include/x86_64-linux-gnu/mpich
+        export CC=clang
+        export CXX=clang++
+        scripts/release/linux.sh -G Ninja -DBUILD_GPU_SUPPORT=ON -DOSPRAY_MODULE_GPU=ON
+      artifact-in: pdf
+      artifact-out: release-sycl-linux
+      artifact-path: build_release/*.gz
+
   release-osx-clang:
     needs: pdf
     secrets: inherit
@@ -66,7 +87,7 @@ jobs:
       cmd: |
         export CC=clang
         export CXX=clang++
-        scripts/release/macosx.sh
+        scripts/release/macosx.sh -DBUILD_EMBREE_FROM_SOURCE=ON # FIXME invalid symlinks in Embree v4.3 package
         $SIGN_FILE_MAC -o runtime -e scripts/release/ospray.entitlements build_release/ospray-*pkg
         scripts/release/macosx_notarization.sh build_release/ospray-*.pkg
       artifact-in: pdf
@@ -80,11 +101,41 @@ jobs:
       force-delete: true    # guarantees .gitattributes are respected in working dir
       runs-on: '["build", "mpi"]'
       cmd: |
-        scripts\release\win.ps1 "Visual Studio 15 2017 Win64"
+        $exitCode = 0 # keep job status to properly fail
+        scripts\release\win.ps1 -G "Visual Studio 15 2017 Win64"
+        $exitCode += $LastExitCode
         & $env:SIGN_FILE_WINDOWS ospray*.msi
+        $exitCode += $LastExitCode
+        exit $exitCode
       artifact-in: pdf
       artifact-out: release-windows
       artifact-path: "build_release/ospray*.zip build_release/ospray*.msi"
+
+
+  release-sycl-windows:
+    needs: pdf
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
+    secrets: inherit
+    with:
+      force-delete: true    # guarantees .gitattributes are respected in working dir
+      runs-on: '["build", "mpi"]'
+      env-from-files: .github/workflows/dpcpp-release.env
+      level-zero-version: public/1.12.0 # for ispcrt
+      cmd: |
+        $env:SYCL_BUNDLE_ROOT = $env:DPCPP_ROOT
+        # disable warnings which lead to excessively large log files
+        $env:CXXFLAGS = '-w'
+        $env:CFLAGS = '-w'
+        $exitCode = 0 # keep job status to properly fail
+        scripts\release\win.ps1 -G Ninja -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DBUILD_GPU_SUPPORT=ON -DOSPRAY_MODULE_GPU=ON
+        $exitCode += $LastExitCode
+        & $env:SIGN_FILE_WINDOWS ospray*.msi
+        $exitCode += $LastExitCode
+        exit $exitCode
+      artifact-in: pdf
+      artifact-out: release-sycl-windows
+      artifact-path: "build_release/ospray*.zip build_release/ospray*.msi"
+
 
 ### SCAN JOBS ###
 
@@ -103,7 +154,7 @@ jobs:
         INSTALL_DIR=$(pwd)/build_deps/install &&
         export CMAKE_PREFIX_PATH=${INSTALL_DIR} &&
         echo "Configure OSPRay" &&
-        cmake -L -S . -B build -DISPC_EXECUTABLE=$INSTALL_DIR/bin/ispc -DTBB_ROOT=$INSTALL_DIR -DOSPRAY_MODULE_DENOISER=ON -DOSPRAY_MODULE_BILINEAR_PATCH=ON -DOSPRAY_MODULE_MPI=ON &&
+        cmake -L -S . -B build -DTBB_ROOT=$INSTALL_DIR -DOSPRAY_MODULE_DENOISER=ON -DOSPRAY_MODULE_BILINEAR_PATCH=ON -DOSPRAY_MODULE_MPI=ON &&
         echo "Done: Configure OSPRay"
       build: cmake --build build
 
@@ -121,6 +172,18 @@ jobs:
       artifact-in-windows: release-windows
       path: build_release/ospray-*
 
+  binary-analysis-sycl:
+    needs:
+      - release-sycl-linux
+      - release-sycl-windows
+    secrets: inherit
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/binary_analysis.yml@main
+    with:
+      project: ospray
+      artifact-in-linux: release-sycl-linux
+      artifact-in-windows: release-sycl-windows
+      path: build_release/ospray-*
+
   antivirus-scan:
     needs:
       - release-linux
@@ -135,6 +198,18 @@ jobs:
       artifact-in-windows: release-windows
       path: build_release/ospray-*
 
+  antivirus-scan-sycl:
+    needs:
+      - release-sycl-linux
+      - release-sycl-windows
+    secrets: inherit
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/antivirus_scan.yml@main
+    with:
+      project: ospray
+      artifact-in-linux: release-sycl-linux
+      artifact-in-windows: release-sycl-windows
+      path: build_release/ospray-*
+
 ### TEST JOBS ###
 
   test-release-linux:
@@ -146,9 +221,58 @@ jobs:
         module load cmake/3.15.2
         module load mpi/mpich-x86_64
         tar -xzf build_release/*.gz
+        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/lib):$LD_LIBRARY_PATH
         export PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/bin):$PATH
         scripts/tests/run_tests.sh $GITHUB_WORKSPACE AVX512SKX TEST_MPI
       artifact-in: release-linux
+
+  test-release-sycl-linux-cpu:
+    needs: release-sycl-linux
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
+    with:
+      image: ubuntu:22.04
+      cmd: |
+        update-alternatives --set mpi /usr/bin/mpicc.mpich
+        update-alternatives --set mpirun /usr/bin/mpirun.mpich
+        tar -xzf build_release/*.gz
+        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/lib):$LD_LIBRARY_PATH
+        export PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/bin):$PATH
+        scripts/tests/run_tests.sh $GITHUB_WORKSPACE AVX512SKX TEST_MPI
+      artifact-in: release-sycl-linux
+
+  test-release-sycl-linux-dg2:
+    needs: release-sycl-linux
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
+    with:
+      image: ubuntu:22.04
+      runs-on: '"dg2"'
+      env-from-files: .github/workflows/gfx-ubuntu22-release.env
+      options: --device=/dev/dri:/dev/dri
+      cmd: |
+        update-alternatives --set mpi /usr/bin/mpicc.mpich
+        update-alternatives --set mpirun /usr/bin/mpirun.mpich
+        tar -xzf build_release/*.gz
+        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/lib):$LD_LIBRARY_PATH
+        export PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/bin):$PATH
+        scripts/tests/run_gpu_tests.sh $GITHUB_WORKSPACE TEST_MPI
+      artifact-in: release-sycl-linux
+
+  test-release-sycl-linux-pvc:
+    needs: release-sycl-linux
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
+    with:
+      image: ubuntu:22.04
+      runs-on: '"pvc"'
+      env-from-files: .github/workflows/gfx-ubuntu22-release.env
+      options: --device=/dev/dri:/dev/dri
+      cmd: |
+        update-alternatives --set mpi /usr/bin/mpicc.mpich
+        update-alternatives --set mpirun /usr/bin/mpirun.mpich
+        tar -xzf build_release/*.gz
+        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/lib):$LD_LIBRARY_PATH
+        export PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/bin):$PATH
+        scripts/tests/run_gpu_tests.sh $GITHUB_WORKSPACE TEST_MPI
+      artifact-in: release-sycl-linux
 
   test-release-osx:
     needs: release-osx-clang
@@ -157,6 +281,7 @@ jobs:
       runs-on: '["x86_64", "build", "avx2"]'
       cmd: |
         unzip build_release/*.zip
+        export DYLD_LIBRARY_PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/lib):$DYLD_LIBRARY_PATH
         export PATH=$GITHUB_WORKSPACE/$(ls -d1 ./ospray-*/bin):$PATH
         scripts/tests/run_tests.sh $GITHUB_WORKSPACE AVX2
       artifact-in: release-osx-clang
@@ -191,8 +316,12 @@ jobs:
       cmd: |
         Expand-Archive build_release/*.zip -DestinationPath .
         $env:Path += ";" + (Get-ChildItem ospray-*\bin | Select-Object -Expand FullName)
+        $exitCode = 0 # keep job status to properly fail
         scripts\tests\run_tests.ps1 $env:GITHUB_WORKSPACE AVX512SKX TEST_MPI
-        & $env:SIGN_FILE_WINDOWS -t (Get-ChildItem ospray-*\bin\* | Select-Object -Expand FullName)
+        $exitCode += $LastExitCode
+        & $env:SIGN_FILE_WINDOWS -t (Get-ChildItem "$env:GITHUB_WORKSPACE\ospray-*\bin\*" | Select-Object -Expand FullName)
+        $exitCode += $LastExitCode
+        exit $exitCode
       artifact-in: release-windows
 
   test-release-windows-msi:
@@ -202,7 +331,67 @@ jobs:
       runs-on: '["avx512", "mpi"]'
       cmd: |
         msiexec.exe /a (Get-ChildItem build_release/*.msi | Select-Object -Expand FullName) /qn TARGETDIR=$env:GITHUB_WORKSPACE
-        $env:Path += ";$env:GITHUB_WORKSPACE\Intel\OSPRay v2\bin"
+        $env:Path += ";$env:GITHUB_WORKSPACE\Intel\OSPRay v3\bin"
+        $exitCode = 0 # keep job status to properly fail
         scripts\tests\run_tests.ps1 $env:GITHUB_WORKSPACE AVX512SKX TEST_MPI
-        & $env:SIGN_FILE_WINDOWS -t $env:GITHUB_WORKSPACE\build_release\*.msi (Get-ChildItem "$env:GITHUB_WORKSPACE\Intel\OSPRay v2\bin\*" | Select-Object -Expand FullName)
+        $exitCode += $LastExitCode
+        & $env:SIGN_FILE_WINDOWS -t $env:GITHUB_WORKSPACE\build_release\*.msi (Get-ChildItem "$env:GITHUB_WORKSPACE\Intel\OSPRay v3\bin\*" | Select-Object -Expand FullName)
+        $exitCode += $LastExitCode
+        exit $exitCode
       artifact-in: release-windows
+
+  test-release-sycl-windows-zip-cpu:
+    needs: release-sycl-windows
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
+    with:
+      runs-on: '["avx512", "mpi"]'
+      cmd: |
+        Expand-Archive build_release/*.zip -DestinationPath .
+        $env:Path += ";" + (Get-ChildItem ospray-*\bin | Select-Object -Expand FullName)
+        $exitCode = 0 # keep job status to properly fail
+        scripts\tests\run_tests.ps1 $env:GITHUB_WORKSPACE AVX512SKX TEST_MPI
+        $exitCode += $LastExitCode
+        & $env:SIGN_FILE_WINDOWS -t (Get-ChildItem "$env:GITHUB_WORKSPACE\ospray-*\bin\*" | Select-Object -Expand FullName)
+        $exitCode += $LastExitCode
+        exit $exitCode
+      artifact-in: release-sycl-windows
+
+  test-release-sycl-windows-msi-cpu:
+    needs: release-sycl-windows
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
+    with:
+      runs-on: '["avx512", "mpi"]'
+      cmd: |
+        msiexec.exe /a (Get-ChildItem build_release/*.msi | Select-Object -Expand FullName) /qn TARGETDIR=$env:GITHUB_WORKSPACE
+        $env:Path += ";$env:GITHUB_WORKSPACE\Intel\OSPRay v3\bin"
+        $exitCode = 0 # keep job status to properly fail
+        scripts\tests\run_tests.ps1 $env:GITHUB_WORKSPACE AVX512SKX TEST_MPI
+        $exitCode += $LastExitCode
+        & $env:SIGN_FILE_WINDOWS -t $env:GITHUB_WORKSPACE\build_release\*.msi (Get-ChildItem "$env:GITHUB_WORKSPACE\Intel\OSPRay v3\bin\*" | Select-Object -Expand FullName)
+        $exitCode += $LastExitCode
+        exit $exitCode
+      artifact-in: release-sycl-windows
+
+  test-release-sycl-windows-zip:
+    needs: release-sycl-windows
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
+    with:
+      runs-on: '["avx512", "mpi", "dg2"]'
+      env-from-files: .github/workflows/gfx-windows-release.env
+      cmd: |
+        Expand-Archive build_release/*.zip -DestinationPath .
+        $env:Path += ";" + (Get-ChildItem ospray-*\bin | Select-Object -Expand FullName)
+        scripts\tests\run_gpu_tests.ps1 $env:GITHUB_WORKSPACE TEST_MPI
+      artifact-in: release-sycl-windows
+
+  test-release-sycl-windows-msi:
+    needs: release-sycl-windows
+    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows_gpu.yml@main
+    with:
+      runs-on: '["avx512", "mpi", "dg2"]'
+      env-from-files: .github/workflows/gfx-windows-release.env
+      cmd: |
+        msiexec.exe /a (Get-ChildItem build_release/*.msi | Select-Object -Expand FullName) /qn TARGETDIR=$env:GITHUB_WORKSPACE
+        $env:Path += ";$env:GITHUB_WORKSPACE\Intel\OSPRay v3\bin"
+        scripts\tests\run_gpu_tests.ps1 $env:GITHUB_WORKSPACE TEST_MPI
+      artifact-in: release-sycl-windows
